# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KraftkitStaging < Formula
  desc "Build and use highly customized and ultra-lightweight unikernels."
  homepage "https://kraftkit.sh"
  version "0.11.5-34-gc0857799"
  license "BSD-3-Clause"

  depends_on "aarch64-elf-binutils"
  depends_on "aarch64-elf-gcc"
  depends_on "coreutils"
  depends_on "gawk"
  depends_on "gnu-sed"
  depends_on "grep"
  depends_on "m4"
  depends_on "make"
  depends_on "qemu"
  depends_on "socat"
  depends_on "wget"
  depends_on "x86_64-elf-binutils"
  depends_on "x86_64-elf-gcc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.11.5-34-gc0857799/kraft_0.11.5-34-gc0857799_darwin_amd64.tar.gz"
      sha256 "b4185c35bd0e8365e4b7e9e0c387e8bb5c5b8c076117b8afa6387215b379ac9c"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.11.5-34-gc0857799/kraft_0.11.5-34-gc0857799_darwin_arm64.tar.gz"
      sha256 "f2e2802cf195c0b68ca5c17c8752716d5a79eb5a41079185b1c39c1e4043ff04"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.11.5-34-gc0857799/kraft_0.11.5-34-gc0857799_linux_amd64.tar.gz"
        sha256 "cf581438e7214d0862304ded5770fbd79d2f02c33a76a42b85288d6b39c8ed4f"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.11.5-34-gc0857799/kraft_0.11.5-34-gc0857799_linux_arm64.tar.gz"
        sha256 "dc712899e69d00b926e852d506ba2f9acbee5e4b7f534ede23abec8e20fa2be1"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
  end
end
