# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KraftkitStaging < Formula
  desc "Build and use highly customized and ultra-lightweight unikernels."
  homepage "https://kraftkit.sh"
  version "0.11.1-16-g1daecc24"
  license "BSD-3-Clause"

  depends_on "aarch64-elf-binutils"
  depends_on "aarch64-elf-gcc"
  depends_on "coreutils"
  depends_on "gawk"
  depends_on "gnu-sed"
  depends_on "grep"
  depends_on "m4"
  depends_on "make"
  depends_on "qemu"
  depends_on "socat"
  depends_on "wget"
  depends_on "x86_64-elf-binutils"
  depends_on "x86_64-elf-gcc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.11.1-16-g1daecc24/kraft_0.11.1-16-g1daecc24_darwin_amd64.tar.gz"
      sha256 "db69cf7a4813a638faaee6e54a5687d589f8ad6fbd28a977abce15c8780e4d63"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.11.1-16-g1daecc24/kraft_0.11.1-16-g1daecc24_darwin_arm64.tar.gz"
      sha256 "f074607429d20e892145394d8a3215e29c0852ac9efb50391427e29d63bdd6b3"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.11.1-16-g1daecc24/kraft_0.11.1-16-g1daecc24_linux_amd64.tar.gz"
        sha256 "5c1178826c94210e4f6a3641a4aabe006d6ac65698d6061a5ef64437ef644cdd"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.11.1-16-g1daecc24/kraft_0.11.1-16-g1daecc24_linux_arm64.tar.gz"
        sha256 "edf11a08b725045e0a405556ab72eedd912f0f9dac05361b4f08bd263bf6cc4a"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
  end
end
