# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kraftkit < Formula
  desc "Build and use highly customized and ultra-lightweight unikernels."
  homepage "https://kraftkit.sh"
  version "0.12.14"
  license "BSD-3-Clause"

  depends_on "aarch64-elf-binutils"
  depends_on "aarch64-elf-gcc"
  depends_on "coreutils"
  depends_on "gawk"
  depends_on "gnu-sed"
  depends_on "grep"
  depends_on "m4"
  depends_on "make"
  depends_on "qemu"
  depends_on "socat"
  depends_on "wget"
  depends_on "x86_64-elf-binutils"
  depends_on "x86_64-elf-gcc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.14/kraft_0.12.14_darwin_amd64.tar.gz"
      sha256 "9d8dee11f500c78d82497b231f9916ee62970735a71c2c00e5314c6d5b8cd046"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.14/kraft_0.12.14_darwin_arm64.tar.gz"
      sha256 "c6148bebd62abd62204264695fedab41e94664986fd40f59eb9770649cee5769"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.14/kraft_0.12.14_linux_amd64.tar.gz"
        sha256 "3c2c4932b4954eab2facd70bf2c64f0b322ee8e024c4e81acb1f4dc6e508e23a"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.14/kraft_0.12.14_linux_arm64.tar.gz"
        sha256 "eb0cd24c4f5c088f51c4dfb6902c91552a86eb3b479b90a0ecc527c6298bacb6"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
  end
end
