# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KraftkitStaging < Formula
  desc "Build and use highly customized and ultra-lightweight unikernels."
  homepage "https://kraftkit.sh"
  version "0.11.6-67-gd79d7804"
  license "BSD-3-Clause"

  depends_on "aarch64-elf-binutils"
  depends_on "aarch64-elf-gcc"
  depends_on "coreutils"
  depends_on "gawk"
  depends_on "gnu-sed"
  depends_on "grep"
  depends_on "m4"
  depends_on "make"
  depends_on "qemu"
  depends_on "socat"
  depends_on "wget"
  depends_on "x86_64-elf-binutils"
  depends_on "x86_64-elf-gcc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.11.6-67-gd79d7804/kraft_0.11.6-67-gd79d7804_darwin_amd64.tar.gz"
      sha256 "9286eb576a40889d50c95acc20877f3800d7fc3ceb11540cf72e453056aaf696"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.11.6-67-gd79d7804/kraft_0.11.6-67-gd79d7804_darwin_arm64.tar.gz"
      sha256 "5b7eae919dab366fa9fee5252e72c8230d525721dd3ec50adfe172c0faa6b0f5"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.11.6-67-gd79d7804/kraft_0.11.6-67-gd79d7804_linux_amd64.tar.gz"
        sha256 "bf26cf3dc67e3299bb8b7109143a35de4e44d16a8b6db33d5a8b281cc531068f"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.11.6-67-gd79d7804/kraft_0.11.6-67-gd79d7804_linux_arm64.tar.gz"
        sha256 "a0453943a2fddedb0ad3663605eea085c4b1906f90874f2d2bf1e8f50a5671d4"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
  end
end
