# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kraftkit < Formula
  desc "Build and use highly customized and ultra-lightweight unikernels."
  homepage "https://kraftkit.sh"
  version "0.12.9"
  license "BSD-3-Clause"

  depends_on "aarch64-elf-binutils"
  depends_on "aarch64-elf-gcc"
  depends_on "coreutils"
  depends_on "gawk"
  depends_on "gnu-sed"
  depends_on "grep"
  depends_on "m4"
  depends_on "make"
  depends_on "qemu"
  depends_on "socat"
  depends_on "wget"
  depends_on "x86_64-elf-binutils"
  depends_on "x86_64-elf-gcc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.9/kraft_0.12.9_darwin_amd64.tar.gz"
      sha256 "999ef110cd0b38343f2787e03aea92e14bfc2080a9231d638ae7b1d3c35677a9"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.9/kraft_0.12.9_darwin_arm64.tar.gz"
      sha256 "19c48f42d08d56917b7cbe4341370f87f07127b6101c9ed74d956f34837a5952"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.9/kraft_0.12.9_linux_amd64.tar.gz"
        sha256 "22f9941b8dabc7679d930ef16530a06c3444867389ec50625ff1ccd81df60107"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.9/kraft_0.12.9_linux_arm64.tar.gz"
        sha256 "c7a54dab58f77bb2ccb9cdb5c79b5f4514333924d5a8955439b5d4fd02a618c0"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
  end
end
