# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unikraft < Formula
  desc "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds."
  homepage "https://unikraft.com"
  version "0.4.0"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/cli/releases/download/v0.4.0/unikraft-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "fbe784ba8ac81b8d6a67f271d6e95c8c01161e81fda4c30991c97067a753faf9"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/cli/releases/download/v0.4.0/unikraft-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "a95d00d4cff0560424d4a506d76527dfc179330ed8bc1097ba9858a7a82fb4a6"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft/cli/releases/download/v0.4.0/unikraft-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "499541a31ce0c24ab16a10df89c7e6cfc3ce12d4aafb3a1ec14dc0e064b7f2ce"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft/cli/releases/download/v0.4.0/unikraft-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "81858c32cab06073f80121e1956992ae76d88e649c62f4c1984ee8fe09505419"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end
end
