# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unikraft < Formula
  desc "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds."
  homepage "https://unikraft.com"
  version "0.2.4"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/cli/releases/download/v0.2.4/unikraft-cli_0.2.4_darwin_amd64.tar.gz"
      sha256 "00ec9da112f527bc61ff01636ddf90e8ef41a76458d3f0f4d10d9b12488cc60d"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/cli/releases/download/v0.2.4/unikraft-cli_0.2.4_darwin_arm64.tar.gz"
      sha256 "733876aa2f0c0dc3d4afaace6353504f657c5f31de34b9261e62ecfb543aa2ae"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft/cli/releases/download/v0.2.4/unikraft-cli_0.2.4_linux_amd64.tar.gz"
      sha256 "3250f37e6c292c36d8d9178c0baaf912d4525906c4cc8c981a4b4dbad84e70d5"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft/cli/releases/download/v0.2.4/unikraft-cli_0.2.4_linux_arm64.tar.gz"
      sha256 "b962973a2f6987bc7159faaa81e1f1f59b546f5559804bfefdab5e0351c0fe99"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end
end
